name: Build Backend
on:
  pull_request:
    paths:
    - 'backend/**'
    - Makefile
    - '.github/**'
  push:
    branches:
      - master
    paths:
    - 'backend/**'
    - Makefile
    - '.github/**'

jobs:

  build:
    name: Lint & Build
    runs-on: ubuntu-18.04

    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15.4'
      id: go

    - name: Check out code
      uses: actions/checkout@v2.3.3

    - name: Lint, Build & Check
      run: |
        cd $GITHUB_WORKSPACE
        make backend-lint
        make backend
